/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/A1-A4/A2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function A2(props) {
  const { nodes, materials } = useGLTF('/A1-A4/A2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.035, 0.018, 0.079]} rotation={[0, 0, -0.105]} scale={0.031}>
        <mesh geometry={nodes['___--__12001'].geometry} material={materials['Default.001']} rotation={[2.407, -Math.PI / 2, 0]} scale={0.03} />
        <mesh geometry={nodes['___--__6001'].geometry} material={materials.Default} rotation={[2.407, -Math.PI / 2, 0]} scale={0.03} />
        <mesh geometry={nodes.___1001.geometry} material={materials['材质.020']} rotation={[2.407, -Math.PI / 2, 0]} scale={0.03} />
        <mesh geometry={nodes.____1001.geometry} material={materials.Default} rotation={[2.407, -Math.PI / 2, 0]} scale={0.03} />
        <mesh geometry={nodes._____6001.geometry} material={materials['Default.001']} rotation={[2.407, -Math.PI / 2, 0]} scale={0.03} />
      </group>
      <group position={[0.002, 0.019, 0.054]} rotation={[0.017, 0, 0]} scale={0.138}>
        <mesh geometry={nodes['Retopo_??002'].geometry} material={materials.螺丝} position={[-0.008, 0.095, 0.05]} rotation={[1.554, 0, 0]} scale={0.386} />
        <mesh geometry={nodes.Retopo_平面004.geometry} material={materials['蓝色.002']} position={[0.003, 0.083, 0.033]} rotation={[1.554, 0, 0]} scale={[0.075, 0.066, 0.066]} />
        <mesh geometry={nodes.Retopo_平面006.geometry} material={materials['镜片玻璃.001']} position={[0.003, -0.035, -0.05]} rotation={[-0.123, 0, 0]} scale={7.249} />
        <mesh geometry={nodes.Retopo_平面007.geometry} material={materials['镜片玻璃.002']} position={[0.003, -0.031, -0.05]} rotation={[-0.123, 0, 0]} scale={7.249}>
          <mesh geometry={nodes.Retopo_平面001.geometry} material={materials['镜片玻璃.002']} />
        </mesh>
        <mesh geometry={nodes.平面003.geometry} material={materials['材质.029']} position={[0.003, -0.03, -0.025]} rotation={[-0.123, 0, -Math.PI / 2]} scale={-0.244} />
        <mesh geometry={nodes.平面004.geometry} material={materials['材质.029']} position={[0.003, -0.03, -0.025]} rotation={[-0.123, 0, -Math.PI / 2]} scale={-0.244} />
        <mesh geometry={nodes.平面005.geometry} material={materials.镜腿黑} position={[0.003, -0.03, -0.025]} rotation={[-0.123, 0, 0]} scale={7.249} />
        <mesh geometry={nodes.平面006.geometry} material={materials['材质.001']} position={[0.003, -0.03, -0.029]} rotation={[0.067, 0, 0]} scale={7.249} />
        <group position={[0.003, -0.033, -0.052]} rotation={[-0.123, 0, 0]} scale={7.249}>
          <mesh geometry={nodes.平面011.geometry} material={materials['材质.006']} />
          <mesh geometry={nodes.平面011_1.geometry} material={materials['材质.014']} />
          <mesh geometry={nodes.平面011_2.geometry} material={materials['材质.015']} />
          <mesh geometry={nodes.平面011_3.geometry} material={materials['材质.016']} />
        </group>
        <mesh geometry={nodes.平面008.geometry} material={materials['材质.017']} position={[0.003, -0.03, -0.027]} rotation={[-0.035, 0, 0]} scale={7.249} />
        <mesh geometry={nodes.柱体004.geometry} material={materials.金螺丝} position={[-0.499, 0.108, -0.133]} rotation={[3.018, -0.825, -Math.PI]} scale={0.006} />
        <mesh geometry={nodes.柱体005.geometry} material={materials.金螺丝} position={[0.504, 0.108, -0.133]} rotation={[-0.123, 0, 0]} scale={0.006} />
        <mesh geometry={nodes.立方体001.geometry} material={materials.螺丝} position={[0.479, 0.104, -0.055]} rotation={[-0.123, 0, 0]} scale={7.249} />
        <mesh geometry={nodes.立方体002.geometry} material={materials.螺丝} position={[-0.474, 0.104, -0.053]} rotation={[-0.123, 0, 0]} scale={7.249} />
      </group>
      <group position={[-0.027, 0.018, 0.079]} rotation={[0, 0, 0.105]} scale={0.031}>
        <mesh geometry={nodes['___--__12'].geometry} material={materials['Default.001']} rotation={[2.407, -1.571, 0]} scale={0.03} />
        <mesh geometry={nodes['___--__6'].geometry} material={materials.Default} rotation={[2.407, -1.571, 0]} scale={0.03} />
        <mesh geometry={nodes.___1.geometry} material={materials['材质.020']} rotation={[2.407, -1.571, 0]} scale={0.03} />
        <mesh geometry={nodes.____1.geometry} material={materials.Default} rotation={[2.407, -1.571, 0]} scale={0.03} />
        <mesh geometry={nodes._____6.geometry} material={materials['Default.001']} rotation={[2.407, -1.571, 0]} scale={0.03} />
      </group>
      <mesh geometry={nodes['Retopo_??017'].geometry} material={materials['default.001']} position={[0.035, 0.026, 0.086]} rotation={[1.579, 0.019, -0.017]} scale={[0.05, 0.048, 0.044]} />
      <mesh geometry={nodes['Retopo_??016'].geometry} material={materials['default.001']} position={[-0.028, 0.026, 0.086]} rotation={[1.579, 0.019, -0.017]} scale={[0.05, 0.048, 0.044]} />
    </group>
  )
}

useGLTF.preload('/A1-A4/A2.glb')
