/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/A1-A4/A3.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function A3(props) {
  const { nodes, materials } = useGLTF('/A1-A4/A3.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.031, 0.024, 0.065]} rotation={[0, 0, -0.105]} scale={0.031}>
        <mesh geometry={nodes['___--__12003'].geometry} material={materials['Default.001']} rotation={[2.407, -Math.PI / 2, 0]} scale={0.03}>
          <mesh geometry={nodes['Retopo_??015'].geometry} material={materials['default.001']} position={[-11.704, -1.434, 0.13]} rotation={[-1.738, 0.737, 1.666]} scale={[53.734, 51.375, 47.261]} />
        </mesh>
        <mesh geometry={nodes['___--__6003'].geometry} material={materials.Default} rotation={[2.407, -Math.PI / 2, 0]} scale={0.03} />
        <mesh geometry={nodes.___1003.geometry} material={materials['材质.020']} rotation={[2.407, -Math.PI / 2, 0]} scale={0.03} />
        <mesh geometry={nodes.____1003.geometry} material={materials.Default} rotation={[2.407, -Math.PI / 2, 0]} scale={0.03} />
        <mesh geometry={nodes._____6003.geometry} material={materials['Default.001']} rotation={[2.407, -Math.PI / 2, 0]} scale={0.03} />
      </group>
      <group position={[-0.031, 0.024, 0.065]} rotation={[0, 0, 0.105]} scale={0.031}>
        <mesh geometry={nodes['___--__12002'].geometry} material={materials['Default.001']} rotation={[2.407, -1.571, 0]} scale={0.03}>
          <mesh geometry={nodes['Retopo_??014'].geometry} material={materials['default.001']} position={[-11.534, -1.722, 0.053]} rotation={[-1.454, 0.74, 1.476]} scale={[53.734, 51.375, 47.261]} />
        </mesh>
        <mesh geometry={nodes['___--__6002'].geometry} material={materials.Default} rotation={[2.407, -1.571, 0]} scale={0.03} />
        <mesh geometry={nodes.___1002.geometry} material={materials['材质.020']} rotation={[2.407, -1.571, 0]} scale={0.03} />
        <mesh geometry={nodes.____1002.geometry} material={materials.Default} rotation={[2.407, -1.571, 0]} scale={0.03} />
        <mesh geometry={nodes._____6002.geometry} material={materials['Default.001']} rotation={[2.407, -1.571, 0]} scale={0.03} />
      </group>
      <group position={[0, 0.02, 0.042]} rotation={[3, 0, Math.PI]} scale={0.174}>
        <mesh geometry={nodes.平面002.geometry} material={materials.镜片玻璃} position={[0, 0, -0.01]} rotation={[-1.637, 0, Math.PI]} scale={[-6.169, 0, -6.169]} />
        <mesh geometry={nodes.平面010.geometry} material={materials['材质.025']} position={[0, 0.001, -0.002]} scale={6.169} />
        <group rotation={[Math.PI / 2, 0, 0]} scale={6.169}>
          <mesh geometry={nodes.平面015.geometry} material={materials.材质2} />
          <mesh geometry={nodes.平面015_1.geometry} material={materials.材质3} />
        </group>
        <mesh geometry={nodes.平面031.geometry} material={materials['材质.023']} position={[0, -0.02, 0.024]} rotation={[-3.123, 0, Math.PI]} scale={6.169} />
        <mesh geometry={nodes.平面034.geometry} material={materials['材质.022']} position={[0, -0.02, 0.025]} rotation={[3.059, 0, -Math.PI]} scale={6.169} />
        <mesh geometry={nodes.柱体010.geometry} material={materials['材质.029']} position={[0, 0.001, 0]} scale={6.169} />
        <mesh geometry={nodes.柱体011.geometry} material={materials['材质.029']} position={[0, 0.001, 0]} scale={6.169} />
        <mesh geometry={nodes.球体.geometry} material={materials['材质.012']} scale={6.169} />
      </group>
    </group>
  )
}

useGLTF.preload('/A1-A4/A3.glb')
