/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 ./public/carbon.glb 
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import * as THREE from "three"
export default function Carbon(props) {
  const { nodes, materials } = useGLTF('carbon.glb')
  console.log(nodes)
  
  const material = useTexture({
    aoMap : "./textures/carbonv2_albedo.jpg",
    normalMap : "./textures/carbonv2_normal.jpg",
  })
  
  const glassMaterial = useTexture({
    roughnessMap : "./glasses/Facade005_1K-JPG_Roughness.jpg",
    normalMap : "./glasses/Facade005_1K-JPG_NormalGL.jpg",
  })
  
  const plasticeMaterial = useTexture({
    normalMap : "./textures/plastic_g_normal.jpg",
    map : "./textures/plastic_g_normal.jpg",
    aoMap : "./textures/plastic_g_normal.jpg",
    roughnessMap : "./textures/plastic_g_normal.jpg",
  })

  const logo = useTexture({
    normalMap : "./textures/new.png",
    map : "./textures/new.png",
    aoMap : "./textures/new.png",
    roughnessMap : "./textures/new.png",
  })

  material.aoMap.repeat.set(5,5)

  material.normalMap.repeat.set(5,5)

  material.normalMap.wrapS =
  material.normalMap.wrapt =
  material.aoMap.wrapt =
  material.aoMap.wraps =
  THREE.RepeatWrapping


  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.carbon_base_large.geometry} material={nodes.carbon_base_large.material} rotation={[1.573, 0, 0]} scale={9.997}>
          <meshStandardMaterial {...material} color={"grey"}/>
        <mesh geometry={nodes.carbon_basetample_large.geometry} material={nodes.carbon_basetample_large.material} >
        </mesh>
        <mesh geometry={nodes.carbon_nosepart_large.geometry} material={nodes.carbon_nosepart_large.material} />
        <mesh geometry={nodes.carbon_temple_large_r.geometry} material={nodes.carbon_temple_large_r.material} >
          <meshStandardMaterial {...plasticeMaterial} color={"#0000ff"}/>

        </mesh>
        <mesh geometry={nodes.carbon_text_large.geometry} material={nodes.carbon_text_large.material} rotation={[-1.57, 0, 0]} scale={0.1} >
          <meshStandardMaterial {...logo} />

        </mesh>
        <mesh geometry={nodes.carbon_glasses_large.geometry} >
          <meshStandardMaterial {...glassMaterial} color={"white"}/>
        </mesh>
        <mesh geometry={nodes.carbon_noserubber_large.geometry} material={nodes.carbon_noserubber_large.material} />
        <mesh geometry={nodes.screw_carbon_large.geometry} material={nodes.screw_carbon_large.material} rotation={[-1.57, 0, 0]} scale={0.1} />
        <mesh geometry={nodes.carbon_temple_large_l.geometry} material={nodes.carbon_temple_large_l.material}>
          <meshStandardMaterial {...plasticeMaterial} color={"#ff0000"}/>

        </mesh>
      </mesh>
    </group>
  )
}

useGLTF.preload('carbon.glb')
