/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/newModel.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function NewModel(props) {
  const { nodes, materials } = useGLTF('newModel.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -0.089, 0]} rotation={[Math.PI / 2, -1.302, Math.PI / 2]} scale={0.584}>
        <group position={[0, 0.007, -0.302]} rotation={[Math.PI, 0, Math.PI]} scale={0.182}>
          <group position={[0, 0, 0.169]} rotation={[0, -1.571, 0]} scale={0.217}>
            <mesh geometry={nodes['__--__1002'].geometry} material={materials['材质.003']} position={[0.703, -0.941, 0]} rotation={[Math.PI, -1.571, 0]} scale={0.118} />
            <mesh geometry={nodes['__--__3'].geometry} material={materials['Default.002']} position={[0.585, -0.779, 0]} rotation={[Math.PI, -1.571, 0]} scale={0.118} />
            <mesh geometry={nodes.___1001.geometry} material={materials['材质.003']} position={[0.348, -0.459, 0.002]} rotation={[Math.PI, -1.571, 0]} scale={0.118} />
            <mesh geometry={nodes.___8.geometry} material={materials['材质.010']} position={[1.01, -1.345, 0]} rotation={[Math.PI, -1.571, 0]} scale={0.118} />
            <mesh geometry={nodes.____2001.geometry} material={materials['Default.002']} position={[0.655, -0.873, 0]} rotation={[Math.PI, -1.571, 0]} scale={0.118} />
          </group>
          <group position={[0, 0.349, 0]} scale={0.691}>
            <mesh geometry={nodes['___--__2'].geometry} material={materials['Default.002']} position={[0, -0.308, -0.01]} rotation={[Math.PI, 0, 0]} scale={0.037} />
            <mesh geometry={nodes['___--__3'].geometry} material={materials['材质.003']} position={[0, 0.148, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.037} />
            <mesh geometry={nodes['___--__3001'].geometry} material={materials['材质.020']} position={[0, 0.148, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.037} />
            <mesh geometry={nodes._____1001.geometry} material={materials['材质.003']} position={[-0.01, -0.215, -0.002]} rotation={[Math.PI, 0, 0]} scale={0.037} />
          </group>
          <mesh geometry={nodes['__--__61'].geometry} material={materials['Default.002']} position={[0.041, -0.028, -0.023]} rotation={[Math.PI, 0, 0]} scale={0.026} />
          <mesh geometry={nodes['__--__62'].geometry} material={materials['Default.002']} position={[0.041, -0.028, 0.017]} rotation={[Math.PI, 0, 0]} scale={0.026} />
          <mesh geometry={nodes['__--__63'].geometry} material={materials['Default.002']} position={[0, -0.028, 0.017]} rotation={[Math.PI, 0, 0]} scale={0.026} />
          <mesh geometry={nodes['__--__64'].geometry} material={materials['Default.002']} position={[-0.041, -0.028, 0.016]} rotation={[Math.PI, 0, 0]} scale={0.026} />
          <mesh geometry={nodes['__--__65'].geometry} material={materials['Default.002']} position={[-0.041, -0.028, -0.023]} rotation={[Math.PI, 0, 0]} scale={0.026} />
          <mesh geometry={nodes.___2002.geometry} material={materials['Default.002']} position={[0, 0, -0.166]} rotation={[Math.PI, 0, 0]} scale={0.026} />
          <mesh geometry={nodes.___4.geometry} material={materials.材质} position={[0, 0.099, -0.002]} rotation={[Math.PI, 0, 0]} scale={0.026} />
          <mesh geometry={nodes.___6.geometry} material={materials['材质.001']} position={[0, 0.007, -0.205]} rotation={[Math.PI, 0, 0]} scale={0.026} />
          <mesh geometry={nodes.____5.geometry} material={materials['材质.001']} position={[0, 0.005, -0.104]} rotation={[Math.PI, 0, 0]} scale={0.026} />
          <mesh geometry={nodes._____1.geometry} material={materials['材质.001']} position={[-0.019, 0.003, 0.102]} rotation={[Math.PI, 0, 0]} scale={0.026} />
        </group>
        <group position={[-0.324, 0.053, 0.014]} rotation={[-0.088, 0, 0]} scale={0.188}>
          <group position={[-0.071, -0.019, 0.615]} rotation={[-3.141, 0, 0]} scale={0.025}>
            <mesh geometry={nodes._____2001_1.geometry} material={materials['材质.008']}/>
            <mesh geometry={nodes._____2001_2.geometry} material={materials['材质.017']} />
          </group>
          <mesh geometry={nodes._____2002.geometry} material={materials['材质.009']} position={[0.333, -0.172, 2.764]} rotation={[-3.141, 0, 0]} scale={0.025} />
        </group>
        <group position={[0.324, 0.053, 0.014]} rotation={[-0.088, 0, 0]} scale={0.188}>
          <group position={[0.068, -0.019, 0.597]} rotation={[-3.141, 0, 0]} scale={0.025}>
            <mesh geometry={nodes._____2003_1.geometry} material={materials['材质.008']} />
            <mesh geometry={nodes._____2003_2.geometry} material={materials['材质.018']} />
          </group>
          <mesh geometry={nodes._____2004.geometry} material={materials['材质.009']} position={[-0.338, -0.169, 2.742]} rotation={[-3.141, 0, 0]} scale={0.025} />
        </group>
        <group position={[0, 0.022, -0.201]} rotation={[0.436, -Math.PI / 2, 0]} scale={0.038}>
          <group position={[-1.208, -0.056, 0]} scale={0.933}>
            <mesh geometry={nodes['__--__1'].geometry} material={nodes['__--__1'].material} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes['___--__10'].geometry} material={materials['材质.001']} position={[1.577, -0.403, -0.008]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes['___--__8'].geometry} material={materials['材质.001']} position={[1.949, -2.002, 0]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes.___2.geometry} material={materials['材质.001']} position={[0.913, 0.059, -0.548]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes.___2003.geometry} material={materials['材质.001']} position={[0, 0, -0.686]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes['____(___)1'].geometry} material={materials['材质.002']} position={[1.283, -0.577, -0.001]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes.____1.geometry} material={materials['材质.001']} position={[1.274, -0.586, 0]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes.____1001.geometry} material={materials.材质} position={[1.274, -0.586, 0]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes.____2.geometry} material={materials.材质} position={[1.283, -0.573, 0]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes['_______50-5003'].geometry} material={materials['材质.005']} position={[-0.524, -4.109, 0]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes['_______50-5004'].geometry} material={materials['材质.005']} position={[-0.524, -4.109, 0]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes['_______50-5006'].geometry} material={materials['材质.005']} position={[-0.524, -4.109, 0]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes['_______50-5007'].geometry} material={materials['材质.003']} position={[-0.524, -4.109, 0]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes['_______50-5008'].geometry} material={materials['材质.003']} position={[-0.524, -4.109, 0]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes['_______50-55'].geometry} material={materials['材质.004']} position={[-0.524, -4.109, 0]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133}>
              <mesh geometry={nodes['Retopo_??002'].geometry} material={nodes['Retopo_??002'].material} position={[31.833, -8.787, 8.859]} rotation={[2.793, 0, 0]} scale={366.445} />
              <mesh geometry={nodes['Retopo_??003'].geometry} material={nodes['Retopo_??003'].material} position={[-32.384, -8.787, 8.859]} rotation={[-0.781, -0.001, 3.133]} scale={[52.314, 12.561, 52.323]} />
            </mesh>
            <mesh geometry={nodes['_______________M2__3(___)_GB_SOCKET_SET_TYPE4_M4X4-C'].geometry} material={nodes['_______________M2__3(___)_GB_SOCKET_SET_TYPE4_M4X4-C'].material} position={[1.528, -1.103, 0.001]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes.Body.geometry} material={materials.材质} position={[1.257, -0.555, 0]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes.Chamfer1.geometry} material={materials['材质.001']} position={[0.276, -0.593, 0.313]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes.Chamfer1002.geometry} material={materials['材质.001']} position={[1.769, -1.19, 0.18]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.133} />
            <mesh geometry={nodes.Chamfer1005.geometry} material={materials['材质.001']} position={[1.284, -2.143, 0]} rotation={[-Math.PI / 2, -0.087, Math.PI / 2]} scale={0.133} />
          </group>
          <mesh geometry={nodes['___--__4'].geometry} material={materials['材质.001']} position={[0.158, -0.585, 0.007]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.124} />
          <mesh geometry={nodes.Chamfer1001.geometry} material={materials['材质.001']} position={[0.443, -1.166, 0.168]} rotation={[Math.PI / 2, -1.484, -Math.PI / 2]} scale={0.124} />
        </group>
        <mesh geometry={nodes['__--__1001'].geometry} material={nodes['__--__1001'].material} position={[0, 0.022, -0.201]} rotation={[3.054, 0, 0]} scale={0.005} />
        <mesh geometry={nodes.___2001.geometry} material={materials['材质.001']} position={[0.019, 0.022, -0.215]} rotation={[3.054, 0, 0]} scale={0.005} />
        <mesh geometry={nodes._____2.geometry} material={materials['材质.007']} position={[0, -0.019, -0.11]} rotation={[3.054, 0, 0]} scale={0.005}>
          <mesh geometry={nodes.___4002.geometry} material={materials['材质.001']} position={[0.076, -9.047, 6.114]} rotation={[0.087, 0, 0]} scale={1.002}>
            <mesh geometry={nodes['__--__2'].geometry} material={materials['材质.010']} position={[-0.171, 12.795, -10.929]} />
            <mesh geometry={nodes.Chamfer1003.geometry} material={materials['材质.001']} position={[-1.401, 8.937, 3.019]} rotation={[-0.087, 0, 0]} scale={0.998} />
          </mesh>
          <mesh geometry={nodes['Retopo_??001'].geometry} material={materials['材质.006']} position={[-0.132, -17.8, 12.808]} rotation={[-0.868, -0.005, -3.07]} scale={86.043} />
        </mesh>
        <mesh geometry={nodes._____2005.geometry} material={materials['材质.002']} position={[0, -0.067, -0.12]} rotation={[3.054, 0, 0]} scale={0.005} />
        <mesh geometry={nodes.___mm_______1.geometry} material={materials['材质.001']} position={[0, 0.023, -0.191]} rotation={[3.054, 0, 0]} scale={0.005} />
        <mesh geometry={nodes.Draft1.geometry} material={nodes.Draft1.material} position={[0, -0.024, -0.141]} rotation={[3.054, 0, 0]} scale={0.005} />
        <mesh geometry={nodes.NURBS路径001.geometry} material={materials['材质.015']} position={[0.11, 0.09, 0.758]} rotation={[-0.269, Math.PI / 2, 0]} scale={0.099} />
        <mesh geometry={nodes.平面002.geometry} material={materials['材质.012']} position={[0.249, 0.065, 0.564]} rotation={[-Math.PI / 2, 0, 1.61]} scale={0.072} />
        <mesh geometry={nodes.平面003.geometry} material={materials['材质.012']} position={[-0.248, 0.065, 0.567]} rotation={[-Math.PI / 2, 0, 1.549]} scale={0.072} />
        <group position={[0.082, 0.156, 0.936]} rotation={[-0.269, Math.PI / 2, 0]} scale={0.016}>
          <mesh geometry={nodes.立方体_1.geometry} material={materials['材质.013']} />
          <mesh geometry={nodes.立方体_2.geometry} material={materials['材质.014']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('newModel.glb')
