/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ./public/A1-A4/test.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Atest(props) {
  const { nodes, materials } = useGLTF('/A1-A4/test.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.立方体007.geometry} material={materials['材质.001']} position={[0.003, 0.045, 0.068]} rotation={[0.017, 0, 0]} scale={0.008} />
      <mesh geometry={nodes.立方体006.geometry} material={materials['材质.001']} position={[0.003, 0.05, 0.076]} rotation={[0.017, 0, 0]} scale={0.008} />
      <mesh geometry={nodes.立方体005.geometry} material={materials['材质.001']} position={[0.003, 0.035, 0.067]} rotation={[0.017, 0, 0]} scale={0.008} />
      <group position={[0.001, 0.03, 0.109]} rotation={[0.454, 0, 0]}>
        <mesh geometry={nodes.柱体001.geometry} material={materials['材质.001']} />
        <mesh geometry={nodes.柱体001_1.geometry} material={materials['材质.006']} />
      </group>
      <mesh geometry={nodes.柱体020.geometry} material={materials['材质.001']} position={[0.007, 0.043, 0.08]} rotation={[2.393, 0, 0]} />
      <mesh geometry={nodes.柱体015.geometry} material={materials['材质.007']} position={[0.003, 0.03, 0.232]} rotation={[0.017, 0, 0]} />
      <mesh geometry={nodes.柱体014.geometry} material={materials['材质.001']} position={[0.007, 0.043, 0.079]} rotation={[2.393, 0, 0]} />
      <mesh geometry={nodes.柱体013.geometry} material={materials['材质.015']} position={[0.007, 0.043, 0.079]} rotation={[2.393, 0, 0]} />
      <group position={[0.002, 0.067, 0.074]} rotation={[-3.124, 0, -Math.PI]}>
        <mesh geometry={nodes.平面001_1.geometry} material={materials['材质.001']} />
        <mesh geometry={nodes.平面001_2.geometry} material={materials['材质.016']} />
      </group>
      <mesh geometry={nodes.平面017.geometry} material={materials['材质.017']} position={[0.002, 0.056, 0.074]} rotation={[0.017, 0, 0]} />
      <mesh geometry={nodes.平面016.geometry} material={materials['材质.021']} position={[0.002, 0.067, 0.074]} rotation={[0.017, 0, 0]} />
      <mesh geometry={nodes.平面015.geometry} material={materials['材质.021']} position={[0.002, 0.056, 0.074]} rotation={[0.017, 0, 0]} scale={[1.147, 1, 1]} />
      <mesh geometry={nodes.平面014.geometry} material={materials['材质.017']} position={[0.003, 0.055, 0.074]} rotation={[-3.124, 0, 0]} />
      <mesh geometry={nodes.平面001.geometry} material={materials['材质.021']} position={[0.003, 0.056, 0.074]} rotation={[-3.124, 0, 0]} scale={[1.147, 1, 1]} />
      <mesh geometry={nodes.Retopo_平面032.geometry} material={materials['材质.022']} position={[0.002, 0.055, 0.073]} rotation={[0.017, 0, 0]} />
      <mesh geometry={nodes.Retopo_平面025.geometry} material={materials['材质.022']} position={[0.003, 0.055, 0.073]} rotation={[0.017, 0, 0]} />
      <mesh geometry={nodes.Retopo_平面023.geometry} material={materials['材质.022']} position={[0.004, 0.055, 0.074]} rotation={[0.017, 0, 0]} />
      <mesh geometry={nodes.Retopo_平面022.geometry} material={materials['材质.022']} position={[0.002, 0.055, 0.074]} rotation={[0.017, 0, 0]} />
      <mesh geometry={nodes.Retopo_平面021.geometry} material={materials['材质.022']} position={[0.001, 0.055, 0.074]} rotation={[0.017, 0, 0]} />
      <mesh geometry={nodes.Retopo_平面031.geometry} material={materials['材质.021']} position={[0.002, 0.055, 0.074]} rotation={[0.017, 0, -Math.PI]} />
      <mesh geometry={nodes.Retopo_平面030.geometry} material={materials['材质.022']} position={[0.004, 0.055, 0.074]} rotation={[0.017, 0, -Math.PI]} />
      <mesh geometry={nodes.Retopo_平面029.geometry} material={materials['材质.022']} position={[0.003, 0.055, 0.074]} rotation={[0.017, 0, -Math.PI]} />
      <mesh geometry={nodes.Retopo_平面028.geometry} material={materials['材质.022']} position={[0.001, 0.055, 0.074]} rotation={[0.017, 0, -Math.PI]} />
      <mesh geometry={nodes.Retopo_平面027.geometry} material={materials['材质.022']} position={[0.003, 0.055, 0.073]} rotation={[0.017, 0, -Math.PI]} />
      <mesh geometry={nodes.Retopo_平面026.geometry} material={materials['材质.022']} position={[0.002, 0.055, 0.073]} rotation={[0.017, 0, -Math.PI]} />
      <mesh geometry={nodes.Retopo_平面024.geometry} material={materials['材质.021']} position={[0.002, 0.056, 0.074]} rotation={[0.017, 0, 0]} />
      <mesh geometry={nodes.asd030002.geometry} material={materials['Lime._asd22220.001']} position={[-0.002, 0.043, 0.079]} rotation={[-3.124, Math.PI / 2, 0]} scale={0.001} />
      <mesh geometry={nodes.asd018003.geometry} material={materials['Lime._asd22220.001']} position={[0.002, 0.041, 0.07]} rotation={[1.588, 0, Math.PI / 2]} scale={[0.001, 0.001, 0]} />
      <mesh geometry={nodes.asd018002.geometry} material={materials['Lime._asd22220.001']} position={[0.007, 0.043, 0.079]} rotation={[-3.124, Math.PI / 2, 0]} scale={[0.001, 0.001, 0]} />
    </group>
  )
}

useGLTF.preload('/A1-A4/test.glb')
