/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf 
Author: PatelDev (https://sketchfab.com/PatelDev)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/earth-f7a76c63ff1846afb2d606e5c8369c15
Title: Earth
*/

import React, { Suspense, useEffect, useState } from 'react'
import { MeshReflectorMaterial, OrbitControls, PresentationControls, Stage, useGLTF, useTexture } from '@react-three/drei'
import Carbon from '../Carbon'
import NewModel from '../NewModel'
import { A1 } from '../A1'
import A2 from '../A2'
import A3 from '../A3'
import A4 from '../A4'
import Atest from '../Test'
import { useRecoilValue } from 'recoil'
import selectFrameAtom from './atoms/selectFrame'
import { Light3d1 } from '../light1'
import { Light3d2 } from '../light2'
import { Light3d3 } from '../light3'
import { Light3d4 } from '../light4'
import selectLightAtom from './atoms/selectLight'
import { DragonFLy } from '../dragonFly'
import selectLoupeAtom from './atoms/selectLoup'


export default function Model(props) {


  const selectFrameValue = useRecoilValue(selectFrameAtom)
  const selectLightValue = useRecoilValue(selectLightAtom)
  const selectLoupeValue = useRecoilValue(selectLoupeAtom)

  const renderModel = () => {
    switch (selectFrameValue) {
      case 1:
        return <A1  />;
      case 2:
        return <A2  />;
      case 3:
        return <A3 />;
      default:
        return null;
    }
  };
  const renderLight = () => {
    switch (selectLightValue) {
      case 1:
        return <Light3d1  />;
      case 2:
        return <Light3d2  />;
      case 3:
        return <Light3d3 />;
        case 4 : 
        return <Light3d4 />;
        
      default:
        return null;
    }
  };
  const renderLoupe = () => {
    switch (selectLoupeValue) {
      case 1:
        return <DragonFLy  />;
      default:
        return null;
    }
  };

  return (

      <Stage environment={"city"} intensity={0.5} >
              {
                renderModel()
              }
              {renderLight()}
              {
                renderLoupe()
              }
      </Stage>

  )
}